baseurl = "http://stsi.ufpa.br"
title = "Semana de Tecnologia e Sistema de Informação"
theme = "dimension"
languageCode = "pt-br"
defaultContentLanguage = "pt"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Semana de Tecnologia e Segurança da Informação"
  description = '<!--[--><h3>Local: Centro de Tecnologia de Informação e Comunicação - CTIC/UFPA <!--]--><br />
                <!--[-->Período: 25 a 29 de Setembro<!--]--><br />
                <!--[-->Horário: 8h às 12h / 14h às 18h00<!--]-->'
  logo = "fa-user-secret"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/cssictic/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"
